use rust_to_ts_types::TypescriptSerializable;
use std::{env, fs, path::PathBuf};

#[derive(TypescriptSerializable)]
struct Test {
    a: String,
    b: String,
}

#[derive(TypescriptSerializable)]
struct Test2 {
    aa: Test,
    test: Option<String>,
}

fn main() {
    // TODO restructure ALL code, so that this can be compile time dependency of the main crate
    // For this, you would need to extract ALL types that are serealized into another types crate

    // generate output string
    println!("Generating ts interface");
    let out_str = Test2::all_types_output()
        .into_iter()
        .fold(String::new(), |a, b| a + &b);

    // write output string
    println!("Exporting ts interface");
    let out_dir = "./../web_client/src/generated/";
    let dest = PathBuf::from(out_dir).join("interface.ts");
    fs::write(
        &dest,
        format!("{}\n{}", "// Generated by /code_generation", out_str).as_bytes(),
    )
    .unwrap();
}
