use rust_to_ts_types::TypescriptSerializable;
// use std::{env, fs, path::PathBuf};

#[derive(TypescriptSerializable)]
struct Test {
    a: String,
    b: String,
}

#[derive(TypescriptSerializable)]
struct Test2 {
    aa: Test,
    test: Option<String>,
}

fn main() {
    // TODO restructure ALL code, so that this can be compile time dependency of the main crate
    // For this, you would need to extract ALL types that are serealized into another types crate

    println!("{}", Test2::serialize_to_type());

    // generate ts interfaces
    // let profile = env::var("PROFILE").unwrap();
    // println!("cargo:warning=Build profile is: {profile}");
    // if profile == "release" {
    //     println!("cargo:warning=Skipping generation of ts interface, as in release the dist files must have already been compiled anyway!");
    // } else {
    //     println!("cargo:warning=Building ts interface now!");
    //     let out_dir = "./../web_client/src/generated/";
    //     let dest = PathBuf::from(out_dir).join("interface.ts");
    //     fs::write(&dest, "// Generated by /build.rs".as_bytes()).unwrap();
    //     println!("cargo:warning=ts interface built");
    // }
}
