use images_cache_builder::IMAGES_CACHE_BUILDER_OUT;
use std::{env, fs, path::PathBuf};

fn main() {
    // rerun only when these change
    println!("cargo:rerun-if-changed=build.rs");
    // println!("cargo:rerun-if-changed=assets/");

    // folder for main code
    println!("cargo:rustc-env=IMAGES_CACHE_BUILDER_OUT={IMAGES_CACHE_BUILDER_OUT}");

    // generate ts interfaces
    let profile = env::var("PROFILE").unwrap();
    println!("cargo:warning=Build profile is: {profile}");
    if profile == "release" {
        println!("cargo:warning=Skipping generation of ts interface, as in release the dist files must have already been compiled anyway!");
    } else {
        println!("cargo:warning=Building ts interface now!");
        let out_dir = "./web_client/src/generated/";
        let dest = PathBuf::from(out_dir).join("interface.ts");
        fs::write(&dest, "// Generated by /build.rs".as_bytes()).unwrap();
        println!("cargo:warning=ts interface built");
    }
}
