use images_cache_builder::{STORAGE_BYTES_ICONS_LOCATION, STORAGE_BYTES_LOCATION};
use std::{env, fs, path::PathBuf};

fn main() {
    // rerun only when these change
    println!("cargo:rerun-if-changed=build.rs");

    // runtime vars to compile time
    println!("cargo:rustc-env=STORAGE_BYTES_LOCATION={STORAGE_BYTES_LOCATION}");
    println!("cargo:rustc-env=STORAGE_BYTES_ICONS_LOCATION={STORAGE_BYTES_ICONS_LOCATION}");

    // generate ts interfaces
    // println!("cargo:rerun-if-changed=..."); // TODO add files that are source for generating the ts exports
    let profile = env::var("PROFILE").unwrap();
    println!("cargo:warning=Build profile is: {profile}");
    if profile == "release" {
        println!("cargo:warning=Skipping generation of ts interface, as in release the dist files must have already been compiled anyway!");
    } else {
        println!("cargo:warning=Building ts interface now!");
        let out_dir = "./web_client/src/generated/";
        let dest = PathBuf::from(out_dir).join("interface.ts");
        fs::write(&dest, "// Generated by /build.rs".as_bytes()).unwrap();
        println!("cargo:warning=ts interface built");
    }
}
