use images_cache_builder::IMAGES_CACHE_BUILDER_OUT;
use std::{fs, path::PathBuf};

fn main() {
    // rerun only when these change
    println!("cargo:rerun-if-changed=build.rs");
    // println!("cargo:rerun-if-changed=assets/");

    // folder for main code
    println!("cargo:rustc-env=IMAGES_CACHE_BUILDER_OUT={IMAGES_CACHE_BUILDER_OUT}");

    // generate ts interfaces
    println!("cargo:warning=Building ts interface now!");
    let out_dir = "./web_client/src/generated/";
    let dest = PathBuf::from(out_dir).join("interface.ts");
    fs::write(&dest, "// Generated by /build.rs".as_bytes()).unwrap();
    println!("cargo:warning=ts interface built");
}
